version: '3'
services:
  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      replicas: 4
      update_config:
        parallelism: 4
        delay: 10s
    networks:
      - app_network
    ports:
      - "63000-63003:5000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
        redis:
          condition: service_healthy
    restart: always
  redis:
    image: redis
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - app_network

volumes:
  redis_data:

networks:
  app_network: