apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    targetRevision: 2.8.0
    chart: eck-operator
    helm:
      values: |
        webhook:
          enabled: false
        config:
          metricsPort: "9100"
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
