apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-external-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.9.0
    helm:
      values: |
        image:
          repository: ghcr.io/external-secrets/external-secrets
        metrics:
          service:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
