version: '3'
services:
  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    restart: always

  redis:
    image: wa-redis
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data:
