apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    common.k8s.elastic.co/type: elasticsearch
    elasticsearch.k8s.elastic.co/cluster-name: elasticsearch
    elasticsearch.k8s.elastic.co/statefulset-name: elasticsearch-es-default
  name: elasticsearch-data-elasticsearch-es-default-0
  namespace: logging
spec:
  accessModes:
    - ReadWriteOnce
  dataSource: null
  resources:
    requests:
      storage: 7Gi
  storageClassName: es-0
  volumeMode: Filesystem
  volumeName: es-pv-0
status:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 7Gi