version: "3"
services:
  web:
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - "9000-9002:5000"
    scale: 3
    networks:
      - app_network
      - backend_network
    volumes:
      - .:/code
    environment:
      FLASK_DEBUG: "true"
      REDIS_HOST: redis
      REDIS_PORT: 6379

  redis:
    image: "redis:alpine"
    volumes:
      - type: volume
        source: mydata
        target: /data
    networks:
      - backend_network

volumes:
  mydata:

networks:
  app_network:
  backend_network: