master_node_count = 1
master_node_prefix = "master"

slave_node_count = 2
slave_node_prefix = "slave"

ubuntu_ver = "ubuntu/jammy64"

cluster_network = "192.168.33"

Vagrant.configure("2") do |config|

  (1..master_node_count).each do |i|
    config.vm.define "#{master_node_prefix}-#{i}" do |node|
      node.vm.box = "#{ubuntu_ver}"
      node.vm.hostname = "#{master_node_prefix}-#{i}"

      node.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.cpus = 2
        vb.name = "#{master_node_prefix}-#{i}" 
        vb.memory = "2048"
      end
      node.vm.network "private_network", ip: "#{cluster_network}.#{i+10}"
        nic_type = "82546GC"
      node.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "docker.yml"
      node.vm.provision "file", source: "key.pub", destination: "~/.ssh/key.pub"
      node.vm.provision "shell", inline: <<-SHELL
        cat /home/vagrant/.ssh/key.pub >> /home/vagrant/.ssh/authorized_keys
      SHELL
      end
    end
  end

  (1..slave_node_count).each do |i|
    config.vm.define "#{slave_node_prefix}-#{i}" do |node|
      node.vm.box = "#{ubuntu_ver}"
      node.vm.hostname = "#{slave_node_prefix}-#{i}"

      node.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.cpus = 2
        vb.name = "#{slave_node_prefix}-#{i}" 
        vb.memory = "1024"
      end
      node.vm.network "private_network", ip: "#{cluster_network}.#{master_node_count+i+10}"
        nic_type = "82546GC"
      node.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y apt-transport-https ca-certificates curl software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
        apt-get update
        apt-get install -y docker-ce
      SHELL
      node.vm.provision "file", source: "key.pub", destination: "~/.ssh/key.pub"
      node.vm.provision "shell", inline: <<-SHELL
        cat /home/vagrant/.ssh/key.pub >> /home/vagrant/.ssh/authorized_keys
      SHELL
    end
  end
end
