#-----------------------------kuard-daemonset-------------------------#

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kuard-daemonset
  namespace : default
spec:
  selector:
    matchLabels:
      app: kuard
  template:
    metadata:
      labels:
        app: kuard
    spec:
      containers:
        - name: kuard
          image: gcr.io/kuar-demo/kuard-amd64:blue
          ports:
            - containerPort: 8080
            
#----------------------------kuard-service-----------------------------#

apiVersion: v1
kind: Service
metadata:
  name: kuard-service
  namespace : default
spec:
  type: NodePort
  selector:
    app: kuard
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 32001