apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret

metadata:
  namespace: demo
  name: new-test-ip-web

spec:
  refreshInterval: "15s"

  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore

  target:
    name: new-ip-web-secret
    template:
      engineVersion: v2
      data:
        DB_HOST: "{{ .rest_api_db_host | toString }}"
        DB_USER: "{{ .rest_api_db_user | toString }}"
        DB_PASSWORD: "{{ .rest_api_db_password | toString }}"
        FAKE_KEY: "fake-fake"

  data:
    - secretKey: rest_api_db_host
      remoteRef:
        key: secret/dev/rest-api
        property: DB_HOST

    - secretKey: rest_api_db_user
      remoteRef:
        key: secret/dev/rest-api
        property: DB_USER

    - secretKey: rest_api_db_password
      remoteRef:
        key: secret/dev/rest-api
        property: DB_PASSWORD